### ISSUE TITLE
Compiler segfaults for mutually recursive functions

### ISSUE THREAD

**Issue by jo5ch** [AnyDSL/impala#73] opened 2017-11-24 14:09 UTC
The compiler segfaults for the following minimal example (impala -emit-thorin):

```
fn a() -> () {
    b();
}

fn b() -> () {
    a();
}
```

Impala commit 983163f8ed0547d8efdaa8700d87291c0a19415c
Thorin commit e015ceea4be10efff7ef3d9a67dc278fc32f07f5

**Comment by madmann91** [comment] 2017-11-24 15:04
This is a duplicate of issue #18. The following compiles fine:

```rust
extern "C" { fn rand() -> int; }
fn a() -> () {
  if rand() % 10 != 0 {
    b();
  }
}

fn b() -> () {
    a();
}
```

**Closed by madmann91** 2017-11-24 15:04 UTC
